#!/bin/bash

#
# Reload dnsmasq service only if $HOSTFILE was changed.
#

HOSTFILE="/var/www/myddns/data/hosts"

[[ ! -f ${HOSTFILE}.md5sum ]] && OLDSUM="" || OLDSUM=$(cat ${HOSTFILE}.md5sum)
NEWSUM=$(md5sum ${HOSTFILE})

if [[ ${OLDSUM} == ${NEWSUM} ]]
then
  echo "WARN: $HOSTFILE was not been changed."
else
  md5sum ${HOSTFILE} > ${HOSTFILE}.md5sum
  service dnsmasq reload
  echo "INFO: $HOSTFILE reload."
fi

